name: listen1_xuan
description: "A new Flutter project."
# git checkout 3.27.4
# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 2.0.0+20

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil:
  shared_preferences: ^2.0.0
  url_launcher: ^6.0.9
  dio: 5.7.0
  flutter_svg: ^2.0.16
  crypto: ^3.0.1
  html: ^0.15.0
  marquee: ^2.3.0
  audioplayers: ^6.1.0
  path_provider: ^2.0.1
  # flutter_local_notifications: ^18.0.1
  audio_service:
    path: packages/audio_service-0.18.18
  audio_session: ^0.2.2
  encrypt: ^5.0.0
  webview_flutter: ^4.10.0
  webview_cookie_manager:
    path: packages/webview_cookie_manager-2.0.6
  dio_cookie_manager: ^3.1.1
  fluttertoast: ^9.0.0
  file_picker: ^8.1.6
  permission_handler: ^11.3.1
  vibration: ^2.0.1
  logger: ^2.5.0
  connectivity_plus: ^6.1.4
  flutter_markdown_plus: ^1.0.5
  archive: ^4.0.2
  install_plugin:
    path: packages/install_plugin-2.1.0
  flutter_isolate: ^2.1.0
  adaptive_theme: ^3.6.0
  preload_page_view: ^0.2.0
  system_info3: ^4.0.1
  animations: ^2.1.0
  loading_animations: ^2.2.0
  media_kit: ^1.2.2 # Primary package.
  media_kit_libs_audio: ^1.0.7 # Native audio dependencies.
  window_manager: ^0.4.2
  webview_windows:
    path: packages/webview_windows
  tray_manager: ^0.5.0
  hotkey_manager: ^0.2.3
  charset_converter: ^2.3.0
  native_dio_adapter: ^1.4.0
  smtc_windows: ^1.0.0
  windows_taskbar:
    path: packages/windows_taskbar-1.1.2
  get:
  shelf: ^1.4.2
  shelf_web_socket: ^3.0.0
  shelf_router: ^1.1.4
  flutter_lyric:
    path: packages/flutter_lyric-2.0.4+6
  # metadata_god: ^1.0.0
  extended_image: ^10.0.1
  mime: ^2.0.0
  # flutter_audio_tagger: ^3.0.3
  # ffmpeg_kit_flutter_new_min: ^2.1.0
  wolt_modal_sheet: ^0.11.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.1
  app_links: ^6.4.1
  msix: ^3.16.12
  win32_registry: ^2.1.0
  # bson: ^5.0.7
  dynamic_color: ^1.8.1
  bonsoir: ^6.0.1
  punycode: ^1.0.0
  iconify_flutter_plus: ^1.0.4
  flutter_launcher_icons: ^0.14.4
  smooth_sheets:
    path: packages/smooth_sheets-0.15.0
  supabase_flutter: ^2.10.3
  badges: ^3.1.2
  scrollview_observer: ^1.26.2
  path: ^1.9.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
msix_config:
  display_name: listen1_xuan
  identity_name: com.xiebian.listen1_xuan
  languages: zh-CN
  install_certificate: false
  protocol_activation: https, listen1-xuan # Add the protocols to activate the app
  app_uri_handler_hosts: listen1-xuan.040905.xyz # Add the app uri handler hosts. You can't use patterns here.
